### ISSUE TITLE
SQL statements logging

### ISSUE THREAD

**Issue by avanov** [aio-libs/aiopg#78]
Hi!
I would like to have sql statements logging right into stdout when I run my applications in a debug mode. Normally (i.e. with a regular sqlalchemy-backed application) I setup the standard python logger with the following structure:

```yaml
logging:
  version: 1
  disable_existing_loggers: True
  formatters:
    generic:
      format: "%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s"

  handlers:
    console:
      level: DEBUG
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: generic

  loggers:
    root:
      level: DEBUG
      handlers: [console]

    asyncio:
      level: DEBUG
      handlers: [console]

    sqlalchemy:
      # "level = INFO" logs SQL queries.
      # "level = DEBUG" logs SQL queries and results.
      # "level = WARN" logs neither.  (Recommended for production systems.)
      level: DEBUG
      handlers: [console]

    sqlalchemy.engine:
      # "level = INFO" logs SQL queries.
      # "level = DEBUG" logs SQL queries and results.
      # "level = WARN" logs neither.  (Recommended for production systems.)
      level: INFO
      handlers: [console]
      propagate: False
```

But apparently this is not enough for aiopg. Just adding the ``aiopg`` logger into that definition makes no difference to the final output. Therefore, the question is how to set it up properly. Is there any working example of it?
